/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jacavi_hal_nat_JNativeCsdLib */

#ifndef _Included_de_jacavi_hal_nat_JNativeCsdLib
#define _Included_de_jacavi_hal_nat_JNativeCsdLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jacavi_hal_nat_JNativeCsdLib
 * Method:    initSensorDetection
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_jacavi_hal_nat_JNativeCsdLib_initSensorDetection
  (JNIEnv *, jobject);

/*
 * Class:     de_jacavi_hal_nat_JNativeCsdLib
 * Method:    releaseSensorDetection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_jacavi_hal_nat_JNativeCsdLib_releaseSensorDetection
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
