/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jacavi_hal_lib42_NativeCsdLib */

#ifndef _Included_de_jacavi_hal_lib42_NativeCsdLib
#define _Included_de_jacavi_hal_lib42_NativeCsdLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jacavi_hal_lib42_NativeCsdLib
 * Method:    initSensorDetection
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_de_jacavi_hal_lib42_NativeCsdLib_initSensorDetection
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_jacavi_hal_lib42_NativeCsdLib
 * Method:    releaseSensorDetection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_jacavi_hal_lib42_NativeCsdLib_releaseSensorDetection
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
