/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jacavi_hal_lib42_NativeLib42 */

#ifndef _Included_de_jacavi_hal_lib42_NativeLib42
#define _Included_de_jacavi_hal_lib42_NativeLib42
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    initLib42
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_jacavi_hal_lib42_NativeLib42_initLib42
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    setSpeed
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_jacavi_hal_lib42_NativeLib42_setSpeed
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    getSpeed
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_jacavi_hal_lib42_NativeLib42_getSpeed
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    toggleSwitch
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_jacavi_hal_lib42_NativeLib42_toggleSwitch
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    getSwitch
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_jacavi_hal_lib42_NativeLib42_getSwitch
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    programmCar
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_jacavi_hal_lib42_NativeLib42_programmCar
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
