/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jacavi_hal_lib42_NativeLib42 */

#ifndef _Included_de_jacavi_hal_lib42_NativeLib42
#define _Included_de_jacavi_hal_lib42_NativeLib42
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    initLib42
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_jacavi_hal_lib42_NativeLib42_initLib42
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    releaseLib42
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_jacavi_hal_lib42_NativeLib42_releaseLib42
  (JNIEnv *, jobject);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    setSpeed
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_jacavi_hal_lib42_NativeLib42_setSpeed
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    getSpeed
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_jacavi_hal_lib42_NativeLib42_getSpeed
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    toggleSwitch
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_jacavi_hal_lib42_NativeLib42_toggleSwitch
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    getSwitch
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_jacavi_hal_lib42_NativeLib42_getSwitch
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    fullBreak
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_jacavi_hal_lib42_NativeLib42_fullBreak
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    activatePacecar
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_jacavi_hal_lib42_NativeLib42_activatePacecar
  (JNIEnv *, jobject);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    deactivatePacecar
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_jacavi_hal_lib42_NativeLib42_deactivatePacecar
  (JNIEnv *, jobject);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    pacecar2box
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_jacavi_hal_lib42_NativeLib42_pacecar2box
  (JNIEnv *, jobject);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    setPacecarSwitch
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_jacavi_hal_lib42_NativeLib42_setPacecarSwitch
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    togglePacecarSwitch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_jacavi_hal_lib42_NativeLib42_togglePacecarSwitch
  (JNIEnv *, jobject);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    setPcPitstop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_jacavi_hal_lib42_NativeLib42_setPcPitstop
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    isPacecarActive
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_jacavi_hal_lib42_NativeLib42_isPacecarActive
  (JNIEnv *, jobject);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    getPcSwitch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_jacavi_hal_lib42_NativeLib42_getPcSwitch
  (JNIEnv *, jobject);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    setPitstop
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_jacavi_hal_lib42_NativeLib42_setPitstop
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    togglePitstop
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_jacavi_hal_lib42_NativeLib42_togglePitstop
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    getPitstop
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_jacavi_hal_lib42_NativeLib42_getPitstop
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    activateFuel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_jacavi_hal_lib42_NativeLib42_activateFuel
  (JNIEnv *, jobject);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    deactivateFuel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_jacavi_hal_lib42_NativeLib42_deactivateFuel
  (JNIEnv *, jobject);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    programmCar
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_jacavi_hal_lib42_NativeLib42_programmCar
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    programmSpeed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_jacavi_hal_lib42_NativeLib42_programmSpeed
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    programmBreak
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_jacavi_hal_lib42_NativeLib42_programmBreak
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    programmFuel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_jacavi_hal_lib42_NativeLib42_programmFuel
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_jacavi_hal_lib42_NativeLib42
 * Method:    resetCars
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_jacavi_hal_lib42_NativeLib42_resetCars
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
